version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node

jobs:
  test:
    <<: *defaults
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn

      # Keep cache
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      # Lint
      - run:
          name: Lint
          command: yarn lint

      # Tests
      - run:
          name: Tests
          command: yarn jest

      # Coverage
      - run:
          name: Coverage
          command: yarn codecov
      
      - persist_to_workspace:
          root: ~/repo
          paths: .
  
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish package
          command: yarn release

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
          
      - release:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
